SET session_replication_role = 'replica';


TRUNCATE TABLE "AdViews" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "Address" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "Advertisements" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "Categories" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "ChatConversation" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "ChatMessages" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "ChatParticipants" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "ChatReadStatus" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "Comments" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "DirectMessages" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "FavoriteStore" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "Followers" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "Invite" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "Likes" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "Order" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "OrderItem" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "Posts" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "Product" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "ProductCategory" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "ProductImage" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "ProductSubCategory" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "ProductVariant" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "ProductVariantSize" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "Profiles" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "User" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "UserCart" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "UserStore" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "notifications" RESTART IDENTITY CASCADE;


SET session_replication_role = 'origin';

SELECT tablename
FROM pg_tables
WHERE schemaname = 'public';